#YAML
name: Deploy to Azure

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: imagebackendregistry.azurecr.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and push image
        run: |
          docker build -t imagebackendregistry.azurecr.io/elari-app:latest .
          docker push imagebackendregistry.azurecr.io/elari-app:latest

      - name: Deploy to App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: elari-app
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          images: imagebackendregistry.azurecr.io/elari-app:latest